name: Trigger auto deployment for runner-functions-nightly63

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: [main]
    paths:
      - "**"
      - ".github/workflows/runner-functions-nightly63-AutoDeployTrigger-31974e9d-09a3-42a1-b083-1bf91bf22ab4.yml"

  # Allow manual trigger
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v3
        with:
          creds: ${{ secrets.RUNNERFUNCTIONSNIGHTLY63_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: docker.io
          registryUsername: ${{ secrets.RUNNERFUNCTIONSNIGHTLY63_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.RUNNERFUNCTIONSNIGHTLY63_REGISTRY_PASSWORD }}
          containerAppName: runner-functions-nightly63
          resourceGroup: swiftfiddle
          imageToBuild: swiftfiddle/runner-functions-nightly63:latest
